### ISSUE TITLE
Build failures with poppler-qt6 21.06.0

### ISSUE THREAD

**Issue by diabonas** [TeXworks/texworks#937]
**Bug description:**
When building TeXworks with the freshly released poppler 21.06.0 against Qt 6, compilation fails with a lot of errors of the form
```
/build/texworks/src/texworks-release-0.6.6/modules/QtPDF/src/backends/PopplerQtBackend.cpp: In function ‘QtPDF::PDFDestination QtPDF::Backend::PopplerQt::toPDFDestination(const Poppler::Document*, const Poppler::LinkDestination&)’:
/build/texworks/src/texworks-release-0.6.6/modules/QtPDF/src/backends/PopplerQtBackend.cpp:53:36: error: cannot convert ‘std::unique_ptr<Poppler::Page>’ to ‘Poppler::Page*’ in initialization
   53 |     ::Poppler::Page * p = doc->page(dest.pageNumber() - 1);
      |                           ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    std::unique_ptr<Poppler::Page>
```
and
```
/build/texworks/src/texworks-release-0.6.6/modules/QtPDF/src/backends/PopplerQtBackend.cpp:721:48: error: no match for ‘operator=’ (operand types are ‘QList<Poppler::Annotation*>’ and ‘std::vector<std::unique_ptr<Poppler::Annotation> >’)
  721 |     popplerAnnots = _poppler_page->annotations();
      |                                                ^
```
This is because upstream commit https://github.com/freedesktop/poppler/commit/45717a50c52ab13f405584eab4e1c586bd39a0ce changed a bunch of pointers to `std::unique_ptr` and `QList` to `std::vector`.

To adapt the code in [`modules/QtPDF/src/backends/PopplerQtBackend.cpp`](https://github.com/TeXworks/texworks/blob/master/modules/QtPDF/src/backends/PopplerQtBackend.cpp) to compile with poppler 21.06.0, we need to use `.get()` to obtain a normal pointer from a `std::unique_ptr` and change `QList` to `std::vector`, cf. the upstream commit linked above for examples.

poppler-qt5 21.06.0 is not affected by this change, so I am building the Arch Linux repository package against Qt 5 for now to solve this issue.

**Steps to reproduce the problem:**

1. Install poppler-qt6 21.06.0 (currently in the Arch Linux [staging] repository).
2. Try to build TeXworks against it (using `cmake -DQT_DEFAULT_MAJOR_VERSION=6`).
3. Oberve the compilation failures shown above.

**Expected behavior:**
Compilation succeeds without errors.

**General information:**
_TeXworks version_: 0.6.6 or current master (d4ec6072b83daa81208ef1f259e55a0df7b46fe2)
_TeXworks obtained from_: [Arch Linux repository](https://archlinux.org/packages/community/x86_64/texworks/) or manual compilation
_Operating system_: Arch Linux

**Additional information:**
Here is a WIP patch that at least makes compilation pass without errors. However it leads to test suite failures, I am not sure whether it is because the patch is faulty or because of unrelated changes in poppler 21.06.0.
```diff
diff --git a/modules/QtPDF/src/backends/PopplerQtBackend.cpp b/modules/QtPDF/src/backends/PopplerQtBackend.cpp
index 373e787f..c85027bb 100644
--- a/modules/QtPDF/src/backends/PopplerQtBackend.cpp
+++ b/modules/QtPDF/src/backends/PopplerQtBackend.cpp
@@ -49,7 +49,7 @@ PDFDestination toPDFDestination(const ::Poppler::Document * doc, const ::Poppler
   // comply with the pdf specs---so we have to convert them back
   qreal w = 1., h = 1.;
   if (doc) {
-    ::Poppler::Page * p = doc->page(dest.pageNumber() - 1);
+    ::Poppler::Page * p = doc->page(dest.pageNumber() - 1).get();
     if (p) {
       w = p->pageSizeF().width();
       h = p->pageSizeF().height();
@@ -143,7 +143,7 @@ void convertAnnotation(Annotation::AbstractAnnotation * dest, const ::Poppler::A
 // ==============
 Document::Document(const QString & fileName):
   Super(fileName),
-  _poppler_doc(::Poppler::Document::load(fileName))
+  _poppler_doc(::Poppler::Document::load(fileName).get())
 {
 #ifdef DEBUG
 //  qDebug() << "PopplerQt::Document::Document(" << fileName << ")";
@@ -176,7 +176,7 @@ void Document::reload()
 
   {
     QMutexLocker l(_poppler_docLock);
-    _poppler_doc = QSharedPointer< ::Poppler::Document >(::Poppler::Document::load(_fileName));
+    _poppler_doc = QSharedPointer< ::Poppler::Document >(::Poppler::Document::load(_fileName).get());
   }
 
   // TODO: possibly unlock the new document again if it was previously unlocked
@@ -334,7 +334,7 @@ PDFDestination Document::resolveDestination(const PDFDestination & namedDestinat
 
   // If the destination could not be resolved (a nullptr or an invalid page
   // number is returned), return an invalid object
-  ::Poppler::LinkDestination * dest = _poppler_doc->linkDestination(namedDestination.destinationName());
+  ::Poppler::LinkDestination * dest = _poppler_doc->linkDestination(namedDestination.destinationName()).get();
   if (dest == nullptr || dest->pageNumber() < 1)
     return PDFDestination();
   return toPDFDestination(_poppler_doc.data(), *dest);
@@ -535,7 +535,7 @@ bool Document::unlock(const QString password)
 Page::Page(Document *parent, int at, QSharedPointer<QReadWriteLock> docLock):
   Super(parent, at, docLock)
 {
-  _poppler_page = QSharedPointer< ::Poppler::Page >(dynamic_cast<Document *>(_parent)->_poppler_doc->page(at));
+  _poppler_page = QSharedPointer< ::Poppler::Page >(dynamic_cast<Document *>(_parent)->_poppler_doc->page(at).get());
   loadTransitionData();
 }
 
@@ -606,8 +606,8 @@ QList< QSharedPointer<Annotation::Link> > Page::loadLinks()
 
   Q_ASSERT(_poppler_page != nullptr);
   _linksLoaded = true;
-  QList< ::Poppler::Link *> popplerLinks;
-  QList< ::Poppler::Annotation *> popplerAnnots;
+  std::vector<std::unique_ptr<Poppler::Link>> popplerLinks;
+  std::vector<std::unique_ptr<Poppler::Annotation>> popplerAnnots;
   {
     // Loading links is not thread safe.
     QMutexLocker popplerDocLock(dynamic_cast<Backend::PopplerQt::Document *>(_parent)->_poppler_docLock);
@@ -623,7 +623,7 @@ QList< QSharedPointer<Annotation::Link> > Page::loadLinks()
   QTransform denormalize = QTransform::fromScale(_poppler_page->pageSizeF().width(), -_poppler_page->pageSizeF().height()).translate(0,  -1);
 
   // Convert poppler links to PDFLinkAnnotations
-  foreach (::Poppler::Link * popplerLink, popplerLinks) {
+  for (const std::unique_ptr<Poppler::Link> &popplerLink : popplerLinks) {
     QSharedPointer<Annotation::Link> link(new Annotation::Link);
 
     // Look up the corresponding ::Poppler::LinkAnnotation object. Do this first
@@ -636,11 +636,11 @@ QList< QSharedPointer<Annotation::Link> > Page::loadLinks()
     // equal, nor does one (necessarily) contain the other.
     // TODO: Can we have the situation that we get more than one matching
     // annotations out of this?
-    foreach (::Poppler::Annotation * popplerAnnot, popplerAnnots) {
+    for (const std::unique_ptr<Poppler::Annotation> &popplerAnnot : popplerAnnots) {
       if (!popplerAnnot || popplerAnnot->subType() != ::Poppler::Annotation::ALink || !denormalize.mapRect(popplerAnnot->boundary()).intersects(link->rect()))
         continue;
 
-      ::Poppler::LinkAnnotation * popplerLinkAnnot = dynamic_cast< ::Poppler::LinkAnnotation *>(popplerAnnot);
+      ::Poppler::LinkAnnotation * popplerLinkAnnot = dynamic_cast< ::Poppler::LinkAnnotation *>(popplerAnnot.get());
       convertAnnotation(link.data(), popplerLinkAnnot, _parent->page(_n));
       // TODO: Does Poppler provide an easy interface to all quadPoints?
       // Note: ::Poppler::LinkAnnotation::HighlightMode is identical to PDFLinkAnnotation::HighlightingMode
@@ -653,7 +653,7 @@ QList< QSharedPointer<Annotation::Link> > Page::loadLinks()
     switch (popplerLink->linkType()) {
       case ::Poppler::Link::Goto:
         {
-          ::Poppler::LinkGoto * popplerGoto = dynamic_cast< ::Poppler::LinkGoto *>(popplerLink);
+          ::Poppler::LinkGoto * popplerGoto = dynamic_cast< ::Poppler::LinkGoto *>(popplerLink.get());
           PDFGotoAction * action = new PDFGotoAction(toPDFDestination(dynamic_cast<Document *>(_parent)->_poppler_doc.data(), popplerGoto->destination()));
           if (popplerGoto->isExternal()) {
             // TODO: Verify that ::Poppler::LinkGoto only refers to pdf files
@@ -667,7 +667,7 @@ QList< QSharedPointer<Annotation::Link> > Page::loadLinks()
         break;
       case ::Poppler::Link::Execute:
         {
-          ::Poppler::LinkExecute * popplerExecute = dynamic_cast< ::Poppler::LinkExecute *>(popplerLink);
+          ::Poppler::LinkExecute * popplerExecute = dynamic_cast< ::Poppler::LinkExecute *>(popplerLink.get());
           if (popplerExecute->parameters().isEmpty())
             link->setActionOnActivation(new PDFLaunchAction(popplerExecute->fileName()));
           else
@@ -675,7 +675,7 @@ QList< QSharedPointer<Annotation::Link> > Page::loadLinks()
         }
         break;
       case ::Poppler::Link::Browse:
-        link->setActionOnActivation(new PDFURIAction(dynamic_cast< ::Poppler::LinkBrowse*>(popplerLink)->url()));
+        link->setActionOnActivation(new PDFURIAction(dynamic_cast< ::Poppler::LinkBrowse*>(popplerLink.get())->url()));
         break;
       /*
       case ::Poppler::Link::Action:
@@ -713,7 +713,7 @@ QList< QSharedPointer<Annotation::AbstractAnnotation> > Page::loadAnnotations()
 
   _annotationsLoaded = true;
 
-  QList< ::Poppler::Annotation *> popplerAnnots;
+  std::vector<std::unique_ptr<Poppler::Annotation>> popplerAnnots;
   {
     // Loading annotations is not thread safe.
     QMutexLocker popplerDocLock(dynamic_cast<Document *>(_parent)->_poppler_docLock);
@@ -727,14 +727,14 @@ QList< QSharedPointer<Annotation::AbstractAnnotation> > Page::loadAnnotations()
   // which fails while we hold a write lock here
   pageLocker.unlock();
 
-  foreach(::Poppler::Annotation * popplerAnnot, popplerAnnots) {
+  for (const std::unique_ptr<Poppler::Annotation> &popplerAnnot : popplerAnnots) {
     if (!popplerAnnot)
       continue;
     switch (popplerAnnot->subType()) {
       case ::Poppler::Annotation::AText:
       {
         Annotation::Text * annot = new Annotation::Text();
-        convertAnnotation(annot, popplerAnnot, _parent->page(_n));
+        convertAnnotation(annot, popplerAnnot.get(), _parent->page(_n));
         pageLocker.relock();
         _annotations << QSharedPointer<Annotation::AbstractAnnotation>(annot);
         pageLocker.unlock();
@@ -743,7 +743,7 @@ QList< QSharedPointer<Annotation::AbstractAnnotation> > Page::loadAnnotations()
       case ::Poppler::Annotation::ACaret:
       {
         Annotation::Caret * annot = new Annotation::Caret();
-        convertAnnotation(annot, popplerAnnot, _parent->page(_n));
+        convertAnnotation(annot, popplerAnnot.get(), _parent->page(_n));
         pageLocker.relock();
         _annotations << QSharedPointer<Annotation::AbstractAnnotation>(annot);
         pageLocker.unlock();
@@ -751,12 +751,12 @@ QList< QSharedPointer<Annotation::AbstractAnnotation> > Page::loadAnnotations()
       }
       case ::Poppler::Annotation::AHighlight:
       {
-        ::Poppler::HighlightAnnotation * popplerHighlight = dynamic_cast< ::Poppler::HighlightAnnotation*>(popplerAnnot);
+        ::Poppler::HighlightAnnotation * popplerHighlight = dynamic_cast< ::Poppler::HighlightAnnotation*>(popplerAnnot.get());
         switch (popplerHighlight->highlightType()) {
           case ::Poppler::HighlightAnnotation::Highlight:
           {
             Annotation::Highlight * annot = new Annotation::Highlight();
-            convertAnnotation(annot, popplerAnnot, _parent->page(_n));
+            convertAnnotation(annot, popplerAnnot.get(), _parent->page(_n));
             pageLocker.relock();
             _annotations << QSharedPointer<Annotation::AbstractAnnotation>(annot);
             pageLocker.unlock();
@@ -765,7 +765,7 @@ QList< QSharedPointer<Annotation::AbstractAnnotation> > Page::loadAnnotations()
           case ::Poppler::HighlightAnnotation::Squiggly:
           {
             Annotation::Squiggly * annot = new Annotation::Squiggly();
-            convertAnnotation(annot, popplerAnnot, _parent->page(_n));
+            convertAnnotation(annot, popplerAnnot.get(), _parent->page(_n));
             pageLocker.relock();
             _annotations << QSharedPointer<Annotation::AbstractAnnotation>(annot);
             pageLocker.unlock();
@@ -774,7 +774,7 @@ QList< QSharedPointer<Annotation::AbstractAnnotation> > Page::loadAnnotations()
           case ::Poppler::HighlightAnnotation::Underline:
           {
             Annotation::Underline * annot = new Annotation::Underline();
-            convertAnnotation(annot, popplerAnnot, _parent->page(_n));
+            convertAnnotation(annot, popplerAnnot.get(), _parent->page(_n));
             pageLocker.relock();
             _annotations << QSharedPointer<Annotation::AbstractAnnotation>(annot);
             pageLocker.unlock();
@@ -783,7 +783,7 @@ QList< QSharedPointer<Annotation::AbstractAnnotation> > Page::loadAnnotations()
           case ::Poppler::HighlightAnnotation::StrikeOut:
           {
             Annotation::StrikeOut * annot = new Annotation::StrikeOut();
-            convertAnnotation(annot, popplerAnnot, _parent->page(_n));
+            convertAnnotation(annot, popplerAnnot.get(), _parent->page(_n));
             pageLocker.relock();
             _annotations << QSharedPointer<Annotation::AbstractAnnotation>(annot);
             pageLocker.unlock();
@@ -931,7 +931,7 @@ QList< Backend::Page::Box > Page::boxes()
   Q_ASSERT(_poppler_page != nullptr);
   QList< Backend::Page::Box > retVal;
 
-  foreach (::Poppler::TextBox * popplerTextBox, _poppler_page->textList()) {
+  for (const std::unique_ptr<Poppler::TextBox> &popplerTextBox : _poppler_page->textList()) {
     if (!popplerTextBox)
       continue;
     Backend::Page::Box box;
@@ -960,11 +960,11 @@ QString Page::selectedText(const QList<QPolygonF> & selection, QMap<int, QRectF>
   bool insertSpace = false;
 
   // Get a list of all boxes
-  QList<Poppler::TextBox*> poppler_boxes = _poppler_page->textList();
+  std::vector<std::unique_ptr<Poppler::TextBox>> poppler_boxes = _poppler_page->textList();
   Poppler::TextBox * lastPopplerBox = nullptr;
 
   // Filter boxes by selection
-  foreach (Poppler::TextBox * poppler_box, poppler_boxes) {
+  for (const std::unique_ptr<Poppler::TextBox> &poppler_box : poppler_boxes) {
     if (!poppler_box)
       continue;
 
@@ -1048,7 +1048,7 @@ QString Page::selectedText(const QList<QPolygonF> & selection, QMap<int, QRectF>
     }
     // Remember the last processed box (required for detecting newlines and
     // inserting spaces)
-    lastPopplerBox = poppler_box;
+    lastPopplerBox = poppler_box.get();
   }
 
   return retVal;
```

**Comment by stloeffler** [comment]
Thanks for reporting and starting a patch. Unfortunately, I don't think the solution will be as easy as adding `.get()` in several places. The reason is that `std::unique_ptr` is an owning pointer, i.e., it destroys the object it manages when it goes out of scope, invalidating the pointer obtained with `.get()`. The "proper" solution will likely require some more thought - and possibly restructuring of the code. I have reached out to the poppler devs to hopefully get more insights.

**Comment by diabonas** [comment]
> Thanks for reporting and starting a patch. Unfortunately, I don't think the solution will be as easy as adding `.get()` in several places. The reason is that `std::unique_ptr` is an owning pointer, i.e., it destroys the object it manages when it goes out of scope, invalidating the pointer obtained with `.get()`.

Ah, that makes sense, and probably explains the test failures es well - I mostly imitated the changes from the upstream poppler commit without paying attention to the scope, so that likely won't work for things like for loops.

> The "proper" solution will likely require some more thought - and possibly restructuring of the code. I have reached out to the poppler devs to hopefully get more insights.

Thank you very much for taking care of this (as well as of TeXworks in general, obviously)!

**Comment by stloeffler** [comment]
poppler-qt6 should be supported (again) since 324e6cacab13092c563ac7cd768907e9867016ff

**Comment by diabonas** [comment]
Hm, there still seem to be some build failures with Qt 6.3.0:
```
In file included from /usr/include/qt6/QtGui/qwindowdefs.h:44,
                 from /usr/include/qt6/QtWidgets/qwidget.h:44,
                 from /usr/include/qt6/QtWidgets/qdialog.h:44,
                 from /usr/include/qt6/QtWidgets/qmessagebox.h:45,
                 from /usr/include/qt6/QtWidgets/QMessageBox:1,
                 from /home/tw/src/scripting/ScriptAPIInterface.h:25,
                 from /home/tw/src/scripting/Script.h:25,
                 from /home/tw/src/TWScriptManager.h:25,
                 from /home/tw/src/TWScriptableWindow.h:25,
                 from /home/tw/src/TWScriptableWindow.cpp:22:
/usr/include/qt6/QtCore/qobjectdefs.h: In instantiation of ‘struct QtPrivate::HasQ_OBJECT_Macro<Tw::Scripting::ScriptLanguageInterface>’:
/usr/include/qt6/QtCore/qobject.h:481:58:   required from ‘T qobject_cast(const QObject*) [with T = Tw::Scripting::ScriptLanguageInterface*]’
/home/tw/src/TWScriptableWindow.cpp:188:107:   required from here
/usr/include/qt6/QtCore/qobjectdefs.h:486:37: error: ‘qt_metacall’ is not a member of ‘Tw::Scripting::ScriptLanguageInterface’
  486 |         enum { Value =  sizeof(test(&Object::qt_metacall)) == sizeof(int) };
      |                                     ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt6/QtWidgets/qwidget.h:45,
                 from /usr/include/qt6/QtWidgets/qdialog.h:44,
                 from /usr/include/qt6/QtWidgets/qmessagebox.h:45,
                 from /usr/include/qt6/QtWidgets/QMessageBox:1,
                 from /home/tw/src/scripting/ScriptAPIInterface.h:25,
                 from /home/tw/src/scripting/Script.h:25,
                 from /home/tw/src/TWScriptManager.h:25,
                 from /home/tw/src/TWScriptableWindow.h:25,
                 from /home/tw/src/TWScriptableWindow.cpp:22:
/usr/include/qt6/QtCore/qobject.h: In instantiation of ‘T qobject_cast(const QObject*) [with T = Tw::Scripting::ScriptLanguageInterface*]’:
/home/tw/src/TWScriptableWindow.cpp:188:107:   required from here
/usr/include/qt6/QtCore/qobject.h:481:58: error: static assertion failed: qobject_cast requires the type to have a Q_OBJECT macro
  481 |     static_assert(QtPrivate::HasQ_OBJECT_Macro<ObjType>::Value,
      |                                                          ^~~~~
/usr/include/qt6/QtCore/qobject.h:481:58: note: ‘QtPrivate::HasQ_OBJECT_Macro<Tw::Scripting::ScriptLanguageInterface>::Value’ evaluates to false
/usr/include/qt6/QtCore/qobject.h:483:53: error: ‘staticMetaObject’ is not a member of ‘ObjType’ {aka ‘Tw::Scripting::ScriptLanguageInterface’}
  483 |     return static_cast<T>(ObjType::staticMetaObject.cast(object));
      |                                    ~~~~~~~~~~~~~~~~~^~~~
```
This happens [in CI](https://github.com/TeXworks/texworks/runs/6030486821?check_suite_focus=true#step:3:1244) as well as on my local system. With Qt 5 everything works as expected.

**Comment by diabonas** [comment]
Awesome, that fixes it, thank you very much :)
