### ISSUE TITLE
Compile failure with qt-5.15

### ISSUE THREAD

**Issue by fedeliallalinea** [TeXworks/texworks#899]
texworks-0.6.5 fails to compile with qt 5.15 returning the error:
```
/var/tmp/portage/app-editors/texworks-0.6.5/work/texworks-release-0.6.5/modules/QtPDF/src/PDFBackend.cpp:744:22: error: aggregate ‘QPainterPath clipPath’ has incomplete type and cannot be defined
  744 |         QPainterPath clipPath;
      |                      ^~~~~~~~
/var/tmp/portage/app-editors/texworks-0.6.5/work/texworks-release-0.6.5/modules/QtPDF/src/PDFBackend.cpp:764:24: error: aggregate ‘QPainterPath pp’ has incomplete type and cannot be defined
  764 |           QPainterPath pp;
      |                        ^~~
```
I also reported bug on gentoo bug tracker with a patch to solve issue https://bugs.gentoo.org/726470

**General information:**
_TeXworks version_:  0.6.5
_Operating system_:  gentoo linux

**Comment by stloeffler** [comment]
Thanks for reporting and supplying the patch. This has already been fixed in the development branch in a5352a3a.
